
	name: Your Workflow Name
	on:
	  push:
		branches:
		  - main
	jobs:
	  build:
		runs-on: ubuntu-latest
		steps:
		  - name: Check out code
			uses: actions/checkout@v2
		  # Add your workflow steps here
				